### PR TITLE
Use Tor for all background connections

### PR DESCRIPTION
**Pull request by Nutomic**
Here's the rest of it. Are there any more connections that I missed?

I didn't really test this one, as I wasn't sure how to.

### CODE REVIEW

**Comment by indywidualny** [comment]
Looks great and everything seems to be thought through. I will also add activity recreation after changing "use tor" setting to make sure we are using the right mode. The activity isn't recreated now due to Android manifest configChanges.

**Comment by Nutomic** [comment]
Great! After this change, it's also really trivial to add a proxy setting. Just add the preference, and return the correct proxy in `Miscellany#getProxy()`. Btw you seem to have a typo in that class name ;)

**Comment by indywidualny** [comment]
Feel free to refactor anything. It was written some time ago and it's not the best.

**Comment by Nutomic** [comment]
I dont really care, just wanted to mention it :)

**Comment by indywidualny** [comment]
I'm trying to test it but on Android Nougat I'm always getting
`java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.net.Proxy.toString()' on a null object reference`

I have no idea what's wrong. Orbot seems to be working fine.

**Comment by Nutomic** [comment]
Can you post the full stack trace for these crashes?

**Comment by indywidualny** [comment]
```
09-28 11:47:17.548 17707-17707/org.indywidualni.fblite W/MainActivity: Failed to set webview proxy
                                                                       java.lang.NullPointerException: Attempt to invoke virtual method 'java.net.SocketAddress java.net.Proxy.address()' on a null object reference
                                                                           at org.indywidualni.fblite.activity.MainActivity.onCreate(MainActivity.java:260)
                                                                           at android.app.Activity.performCreate(Activity.java:6664)
                                                                           at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
                                                                           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2599)
                                                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707)
                                                                           at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                           at android.os.Looper.loop(Looper.java:154)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:6077)
                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
```

```
09-28 11:52:28.774 17707-17707/org.indywidualni.fblite W/System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.net.Proxy.toString()' on a null object reference
09-28 11:52:28.775 17707-17707/org.indywidualni.fblite W/System.err:     at org.indywidualni.fblite.fragment.SettingsFragment.onResume(SettingsFragment.java:158)
09-28 11:52:28.775 17707-17707/org.indywidualni.fblite W/System.err:     at android.app.Fragment.performResume(Fragment.java:2398)
09-28 11:52:28.775 17707-17707/org.indywidualni.fblite W/System.err:     at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1032)
09-28 11:52:28.775 17707-17707/org.indywidualni.fblite W/System.err:     at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1171)
09-28 11:52:28.775 17707-17707/org.indywidualni.fblite W/System.err:     at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1153)
09-28 11:52:28.775 17707-17707/org.indywidualni.fblite W/System.err:     at android.app.FragmentManagerImpl.dispatchResume(FragmentManager.java:2049)
09-28 11:52:28.775 17707-17707/org.indywidualni.fblite W/System.err:     at android.app.FragmentController.dispatchResume(FragmentController.java:198)
09-28 11:52:28.775 17707-17707/org.indywidualni.fblite W/System.err:     at android.app.Activity.performResume(Activity.java:6789)
09-28 11:52:28.775 17707-17707/org.indywidualni.fblite W/System.err:     at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3377)
09-28 11:52:28.775 17707-17707/org.indywidualni.fblite W/System.err:     at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3440)
09-28 11:52:28.775 17707-17707/org.indywidualni.fblite W/System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2713)
09-28 11:52:28.775 17707-17707/org.indywidualni.fblite W/System.err:     at android.app.ActivityThread.-wrap12(ActivityThread.java)
09-28 11:52:28.775 17707-17707/org.indywidualni.fblite W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460)
09-28 11:52:28.775 17707-17707/org.indywidualni.fblite W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
09-28 11:52:28.775 17707-17707/org.indywidualni.fblite W/System.err:     at android.os.Looper.loop(Looper.java:154)
09-28 11:52:28.775 17707-17707/org.indywidualni.fblite W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6077)
09-28 11:52:28.775 17707-17707/org.indywidualni.fblite W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
09-28 11:52:28.775 17707-17707/org.indywidualni.fblite W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
09-28 11:52:28.775 17707-17707/org.indywidualni.fblite W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
```

**Pull request merged**
