### PR TITLE
black theme

### PR DESCRIPTION
**Pull request by drbeat**
blacked search
decreased eyehurting white borders

### CODE REVIEW

**Comment by drbeat** [comment]
this is much better. 
but since ive got a device with amoled display i will try to tune the css more and more

**Comment by indywidualny** [comment]
Awesome! Thanks :)

**Comment by indywidualny** [comment]
Some things are missing. I have to mix it with the old version. Loading spinner, a few backgrounds and buttons. Good job anyway :)

**Comment by drbeat** [comment]
Ooops. I may have accidently deleted them.
I'll look into improving it later :).
Thanks for the feedback!
Am 13.11.2015 10:00 vorm. schrieb "Krzysztof Grabowski" <
notifications@github.com>:

**Comment by indywidualny** [comment]
Ok. I will wait a few days with a new release. Do some changes, add some removed lines. It's up to you. I will not edit this file in that case. No deadlines.

**Pull request merged**
