### PR TITLE
Traslate to Portuguese

### PR DESCRIPTION
**Pull request by antun3s**

### CODE REVIEW

**Comment by indywidualny** [comment]
Awesome!

**Comment by antun3s** [comment]
I'm sorry for the noob question, it is the first project to contribute.
How can I compile FaceSlim?

**Comment by indywidualny** [comment]
Well. I'm building it in Android Studio. You may use this program to build an app however you would need to install a lot of Android SDK components (several GB). It would also be a version with a different signing key so you wouldn't have a possibility to update the app on your phone, just clean install it.

I suppose you want to test the changes on your device. I've built it for ya ;)
https://github.com/indywidualny/FaceSlim/blob/df1bd6e074262b989ce68cabc8e78ebbb3353de4/app/app-release.apk

Check it out. If you want to have a possibility to build it on your own, do just like I said. Import this project into Android Studio, even directly from Github and build it.

**Comment by antun3s** [comment]
Thank you very much @indywidualny :D

**Pull request merged**
