### PR TITLE
strings-ro.xml

### PR DESCRIPTION
**Pull request by IulianSz**
Hi. I just translate your english strings.xml in Romanian.
I don't know how to add a new different file with a new name and preserve the existing one - so please if you need to include this translation in your application - do the preparations needed. I propose the name for it to be strings-ro.xml.

Best regards and good luck with your app. Is nice.
Iulian

### CODE REVIEW

**Comment by pecuna** [comment]
Hi!
In order to translate the app you need to fork the github repo to your 
account and clone it to your pc  and create a new directory in 
FaceSlim\app\src\main\res named values-ro and paste there the translated 
strings.xml.  Update your repo in github and finally make a Push request 
to the original FaceSlim. After your request approval changes will be 
merged.

-- 
Regards
pecuna91

**Comment by IulianSz** [comment]
Ok. When i will find the necesary time i will do it. Thanks!

**Comment by indywidualny** [comment]
Should I do it manually? I can also wait for you to fork the repo and do just like @pecuna said ;)

**Comment by IulianSz** [comment]
Hi
If you want please do it manually because i don't have Github Desktop installed at work, at home i dont have time to do it and eventually when i will manage to do it will be too late....

So, do it for me with thanks

Best
Iulian

**Comment by indywidualny** [comment]
Done, thanks!

**Pull request closed without merging**
